### PR TITLE
Added 'normal' to calCurves

### PR DESCRIPTION
**Pull request by f-silva-archaeo**
Created a normal.14C and added 'normal' as a possible calCurve in calibrate() to help with datasets that combine 14C and other radiometric dates that don't use calibration curve

### CODE REVIEW

**Comment by ahb108** [comment]
Just checking whether 'normal' is the write word (because it might imply a distributional shape)? Is it basically just a straight line y=x?

**Comment by ercrema** [comment]
It's basically a straight line between 50000 and -500 calBP. I think Bchron also refers to this as normal so I think its fine and we can merge.

**Comment by stonexsky** [comment]
Hi guys

Yes the wording comes from Bchron but maybe“flat” is more appropriate or something similar

Thoughts?

F


—

Fabio Silva, PhD

Research Associate, UCL Institute of Archaeology

Tutor, Sophia Centre for the Study of Cosmology in Culture, University of Wales Trinity Saint David

Secretary, European Society for Astronomy in Culture (SEAC)

Co-Founder and Co-Editor, Journal of Skyscape Archaeology<http://equinoxpub.com/JSA> (JSA)

Website & blog: www.skyscaper.net<http://www.skyscaper.net>

On 24 Apr 2018, 9:20 PM +0200, Enrico R. Crema <notifications@github.com>, wrote:

It's basically a straight line between 50000 and -500 calBP. I think Bchron also refers to this as normal so I think its fine and we can merge.

**Comment by ercrema** [comment]
I think normal is fine - I'll add a header on the file referencing Bchron.

**Pull request merged**
