### PR TITLE
Updated calibration functions to refer to new 2020 curves, added new 2020 curves to appropriate folder

### PR DESCRIPTION
**Pull request by philriris**

### CODE REVIEW

**Comment by ercrema** [comment]
Thanks Phil. I will add references to intcal13 in the doc to allow for backwark compatibility

**Comment by philriris** [comment]
devtools::install_github currently throws an error in calibration.R:

55:76: unexpected input
54: 
55: calibrate.default <- function(x, errors, ids=NA, dateDetails=NA, calCurves=‘
                                                                                                                             ^
ERROR: unable to collate and parse R files for package 'rcarbon'

**Comment by pmschauer** [comment]
There were curly quotes around intcal20 in line 55, which is why that failed. Change that and it should work.

**Comment by pmschauer** [comment]
Also line 208. Looks like wherever intcal20 was changed the quotes are the wrong type.

**Comment by philriris** [comment]
Serves me right for doing a ctrl+F -> replace outside of R.

**Pull request merged**
